### ISSUE TITLE
Current comsat on maven is using an out of date dropwizard

### ISSUE THREAD

**Issue by felixgao** [puniverse/comsat#30]
version 0.30.0 is using an out dated version of dropwizard and pulls in com.codahale.metrics:metrics-core instead of io.dropwizard.metrics:metrics-core.  

+--- co.paralleluniverse:comsat-dropwizard:0.3.0
|    +--- io.dropwizard:dropwizard-jdbi:0.7.1
|    |    +--- io.dropwizard:dropwizard-db:0.7.1
|    |    |    +--- io.dropwizard:dropwizard-core:0.7.1 -> 0.8.1 (*)
|    |    |    \--- org.apache.tomcat:tomcat-jdbc:7.0.50
|    |    |         \--- org.apache.tomcat:tomcat-juli:7.0.50
|    |    +--- org.jdbi:jdbi:2.55
|    |    |    \--- com.google.code.findbugs:annotations:2.0.3 -> 3.0.0
|    |    \--- com.codahale.metrics:metrics-jdbi:3.0.2
|    |         \--- com.codahale.metrics:metrics-core:3.0.2
|    +--- com.google.guava:guava:18.0
|    +--- io.dropwizard:dropwizard-core:0.7.1 -> 0.8.1 (*)
|    +--- co.paralleluniverse:comsat-jdbi:0.3.0
|    |    +--- org.jdbi:jdbi:2.55 (*)
|    |    +--- com.google.guava:guava:18.0
|    |    \--- co.paralleluniverse:comsat-jdbc:0.3.0
|    |         \--- com.google.guava:guava:18.0
|    +--- co.paralleluniverse:comsat-httpclient:0.3.0 (*)
|    +--- co.paralleluniverse:comsat-servlet:0.3.0
|    |    \--- com.google.guava:guava:18.0
|    \--- io.dropwizard:dropwizard-client:0.7.1
|         +--- io.dropwizard:dropwizard-core:0.7.1 -> 0.8.1 (*)
|         +--- com.sun.jersey:jersey-client:1.18.1
|         |    \--- com.sun.jersey:jersey-core:1.18.1
|         +--- com.sun.jersey.contribs:jersey-apache-client4:1.18.1
|         |    \--- com.sun.jersey:jersey-client:1.18.1 (*)
|         +--- org.apache.httpcomponents:httpclient:4.3.4 -> 4.4 (*)
|         \--- com.codahale.metrics:metrics-httpclient:3.0.2
|              \--- com.codahale.metrics:metrics-core:3.0.2

which causes the application to crash with the following error
Exception in thread "main" java.lang.NoSuchMethodError: com.codahale.metrics.JmxAttributeGauge.<init>(Ljavax/management/MBeanServerConnection;Ljavax/management/ObjectName;Ljava/lang/String;)V
	at com.codahale.metrics.jvm.BufferPoolMetricSet.getMetrics(BufferPoolMetricSet.java:45)
	at com.codahale.metrics.MetricRegistry.registerAll(MetricRegistry.java:381)
	at com.codahale.metrics.MetricRegistry.register(MetricRegistry.java:85)
	at io.dropwizard.setup.Bootstrap.<init>(Bootstrap.java:76)
	at io.dropwizard.Application.run(Application.java:68)

**Comment by felixgao** [comment]
seems like up coming version 0.40 is using the newer version.  will look forward for the new version.
